DEFINE
  VAR _LatestDate =
    MAXX(FILTER(ALL('Fecha'[Date]), NOT ISBLANK(CALCULATE([Facturacion]))), 'Fecha'[Date])
  VAR _CurrentMonth =
    DATESBETWEEN('Fecha'[Date], DATE(YEAR(_LatestDate), MONTH(_LatestDate), 1), EOMONTH(_LatestDate, 0))
  VAR _Core =
    SUMMARIZECOLUMNS(
      'Canal'[Channel Group],
      'Canal'[Sales Channel],
      _CurrentMonth,
      "Revenue", [Facturacion],
      "Margin", [Margen],
      "Orders", [# Pedidos]
    )
  VAR _TotalRevenue = SUMX(_Core, [Revenue])

EVALUATE
ADDCOLUMNS(_Core, "Revenue Share", DIVIDE([Revenue], _TotalRevenue))
ORDER BY 'Canal'[Channel Group], [Revenue] DESC
