DEFINE
  VAR _DateWindow =
    FILTER(
      ALL('Fecha'[Date]),
      'Fecha'[Date] >= DATE(2025, 1, 1) &&
      'Fecha'[Date] <= DATE(2026, 12, 31)
    )

EVALUATE
SUMMARIZECOLUMNS(
  'Region'[Region],
  'Canal'[Channel Group],
  'Canal'[Sales Channel],
  _DateWindow,
  "Revenue", [Facturacion],
  "Margin", [Margen],
  "Margin Percent", [Margen (%)],
  "Orders", [# Pedidos]
)
ORDER BY 'Region'[Region], [Revenue] DESC
